
# The name of the bucket.
# eg. "my-bucket".
bucket_name = ""

# The endpoint URL for the bucket.
# eg. "https://<...>.r2.cloudflarestorage.com"
endpoint_url = ""

# The key ID for the bucket.
key_id = ""

# The secret key for the bucket.
secret_key = ""

# The region for the bucket. "auto" is sometimes fine.
region = "auto"
